### ISSUE TITLE
[Suggestion for improvement] Re-enable when TAB change

### ISSUE THREAD

**Issue by crssi** [Aaron-P/ToggleResistFingerprinting#3]
When someone change the TAB `onActivated` the FPI should change back to ON... so its not left forgoten at OFF state. 😉 

Cheers

**Comment by Aaron-P** [comment]
This seems to be related to #2 , the handling of this may be complicated because resist fingerprinting is a global setting, not tab specific, and tabs are active in the background.  So for example, if you have some tab open that you want resist fingerprinting on for, and then go to a tab you want it off for, the other tab can still be fingerprinting you while you are on the "good" tab.

I have some ideas on how to handle this sort of thing, but there really isn't a one fits all solution, so I will have to leave it up to the user to choose from various options.

**Comment by crssi** [comment]
I know that FPI is global, that is why suggested.
`onActivated` event I meant and not active tab. When tab change the `onActivated` event is triggered.

So if someone is on specific tab where the need is to turn off RFP, like apple login to icloud (see https://bugzilla.mozilla.org/show_bug.cgi?id=1621729), the user turn it off and not to forget to turn it back on it would be nice that when this tab is closed or changed to inactive the RFP should be set back to ON.

This is not related to #2, since I am talking on temporary/short time turning off.

Cheers

**Comment by Aaron-P** [comment]
It is related in that it doesn't have a one size fits all solution. Disabling fingerprinting while there are any other non-disposed tabs exposes your "real" fingerprint to those tabs. What level of exposure the user is willing to deal with is up to the user, the only difference here vs #2 is essentially automatically disabling when going to a specific site vs temporarily disabling when clicking the button or something like that.  The risks with disabling _at all_ are the same.

**Comment by crssi** [comment]
Huh... I got a wrong impression that point of your extension is meant that RFP=resistFingerPrinting is always enabled=true, but with option to disable when needed.

Sorry to bother and cheers

**Comment by Aaron-P** [comment]
That is the goal, but some people are less inclined to do that manually and want some automated whitelist to handle it. It could potentially be used either way, but those usages are somewhat conflicting in how the enable/disabling are to be handled in automated ways, and both have the issue of exposing real values when resist fingerprinting is disabled.  So I am considering how to handle all of these possible options, and give the choice to the user via configuration.
